version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${CB_DB_NAME}
      MYSQL_USER: ${CB_DB_USERNAME}
      MYSQL_PASSWORD: ${CB_DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    volumes:
      - chartbrew-db:/var/lib/mysql

  chartbrew:
    build: .
    restart: always
    ports:
      - 4018:4018
      - 4019:4019
    expose:
      - 4018
      - 4019
    depends_on:
      - db
    links:
      - db

volumes:
  chartbrew-db: